### ISSUE TITLE
Support get_vector_direction

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/wordvecspace#17]
We have `get_vector_magnitudes`. Along these lines we need to support `get_vector_direction` which returns the angle of the vector. Combining the angle and magnitude information about a vector, we should be able to recompute the original vector coordinates.

**Comment by RamanjaneyuluIdavalapati** [comment]
As it is not possible to find the angle of a single vector (with more than two dimensions), I am closing the issue.
