### ISSUE TITLE
Avoid using temp file in WordVecSpaceFile module

### ISSUE THREAD

**Issue by chatrapathik** [deep-compute/wordvecspace#28]
- @prashanthellina we are writing the words into the temp file, then we are accessing this temp file as input for C Minimal Perfect Hashing.
- As per our discussion, writing word data into temp file is not good a mechanism.
- So we need to find a better mechanism by avoiding writing data into a temp file.

**Comment by RamanjaneyuluIdavalapati** [comment]
- I hope this is not required as the wordvecspace data format is changed.
