### ISSUE TITLE
get_nearest operation does not support passing a vector, vector and token together and list of vectors

### ISSUE THREAD

**Issue by shivam05011996** [deep-compute/wordvecspace#37]
In the current implementation of the get_nearest operation, we don't have the options to pass a vector,
a vector and a token, list of vectors.

**Comment by RamanjaneyuluIdavalapati** [comment]
@shivam05011996  As discussed we can pass the array of vectors with the shape n*dimension.
n -> total number of the vectors
dimension -> dimension of the vectors

But I am keeping this open as passing list of vectors (ex: [vec1, vec2]) and list of vectors along with tokens or indices (Ex: [vec1, vec2, 2, 'the']) is not supported yet.

**Comment by shivam05011996** [comment]
@RamanjaneyuluIdavalapati okay

**Comment by shivam05011996** [comment]
We will try to resume the work on this, in the near future

**Comment by shivam05011996** [comment]
Moving to ready.

**Comment by shivam05011996** [comment]
Working on different issue, moving to ready
